namespace Gamelogic.Grids2.Graph
{
	/// <summary>
	/// A shape of a single cell at the origin.
	/// </summary>
	/// <seealso cref="Gamelogic.Grids2.Graph.PrimitiveShapeNode{Gamelogic.Grids2.GridPoint2}" />
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for SingleShape2Node
	[ShapeNode("All/Single", 2)]
	public class SingleShape2Node : PrimitiveShapeNode<GridPoint2>
	{
		protected override IExplicitShape<GridPoint2> Generate()
		{
			return ImplicitShape
				.Single2()
				.ToExplicit(new GridRect(GridPoint2.Zero, GridPoint2.One));
		}
	}
}